apiVersion: audit.kubeorthos.io/v1alpha1
kind: ClusterRule
metadata:
  labels:
    app.kubernetes.io/name: kubeorthos
    app.kubernetes.io/managed-by: kustomize
  name: clusterrule-sample
spec:
  action: Audit
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  expectedNodeConfig:
    kubeletVersion: v1.34.3
    containerRuntime: containerd://2.2.0
    kernelVersion: 6.12.76-linuxkit
    osImage: Debian GNU/Linux 12 (bookworm)
    architecture: arm64
  expectedConditions:
    - type: Ready
      status: "True"
    - type: MemoryPressure
      status: "False"
    - type: DiskPressure
      status: "False"
  minimumResources:
    cpu: "20"
    memory: "2Gi"
    storage: "10Gi"
